name: On PR Trigger (LLM)

on:
  push:
    branches:
      - tmp-fix-release-env
    
permissions:
  contents: read
  pull-requests: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  PKG_DIR: packages/qvac-lib-infer-llamacpp-llm

jobs:  
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret is present
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "NPM_TOKEN length: ${#NPM_TOKEN}"
          echo "PAT_TOKEN length: ${#PAT_TOKEN}"

  # cpp-lint:
  #   uses: tetherto/qvac-devops/.github/workflows/cpp-lint.yaml@v1.1.7
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  #   with:
  #     sha: ${{ github.event.pull_request.base.sha }}
  #     pr_head_sha: ${{ github.event.pull_request.head.sha }}
  #     workdir: packages/qvac-lib-infer-llamacpp-llm
